Repository yauhofung/TTP0-CapstoneProject, pull requests merged in 2021-01, with the labels that each got.

#6 User Stories
  outline.md
Labels: documentation

#7 Clarified outline headings
  outline.md
Labels: enhancement

#8 Linked sketches in outline.md
  outline.md
Labels: enhancement

#10 Added React boilerplate
  .gitignore
  package-lock.json
  package.json
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  public/robots.txt
  src/App.js
  src/App.test.js
  src/index.css
  src/index.js
  src/reportWebVitals.js
  src/setupTests.js
Labels: good first issue

#25 Added Textfields, Button, and Grid
  src/App.js
  src/components/Navbar.js
  src/pages/AdvancedSearch.js
Labels: enhancement

#27 Moved home page content to Home.js
  src/App.js
  src/pages/Home.js
Labels: enhancement

#40 Yauho warnings
  src/components/MovieList.js
  src/components/MoviePage.js
  src/components/Pagination.js
  src/components/SearchBar.js
  src/pages/AdvancedSearch.js
Labels: enhancement

#48 Applied Kris' 100 char limit to SearchBar.js
  src/components/SearchBar.js
  src/pages/AdvancedSearch.js
Labels: enhancement
